In [1]:
import numpy as np

# Create the array
array = np.random.randint(1, 101, size=(5, 5))
print("Original Array:")
print(array)


Original Array:
[[80 35 39 11 34]
 [17 17 67 24 78]
 [50 65  6 68 97]
 [41 82 84 27 74]
 [47 16 74 66 59]]


In [2]:
middle_element = array[2, 2]
print("\nMiddle Element:")
print(middle_element)



Middle Element:
6


In [3]:
mean_of_rows = np.mean(array, axis=1)
print("\nMean of Each Row:")
print(mean_of_rows)
 


Mean of Each Row:
[39.8 40.6 57.2 61.6 52.4]


In [4]:
overall_mean = np.mean(array)
new_array = array[array > overall_mean]
print("\nElements Greater Than Overall Mean:")
print(new_array)



Elements Greater Than Overall Mean:
[80 67 78 65 68 97 82 84 74 74 66 59]


In [5]:
def numpy_spiral_order(matrix):
    result = []
    while matrix.size:
        result += matrix[0].tolist()
        matrix = np.rot90(matrix[1:])
    return result

# Example usage
spiral_order = numpy_spiral_order(array)
print("\nSpiral Order:")
print(spiral_order)



Spiral Order:
[80, 35, 39, 11, 34, 78, 97, 74, 59, 66, 74, 16, 47, 41, 50, 17, 17, 67, 24, 68, 27, 84, 82, 65, 6]
